myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users_auth.urls")),
]

myproject/users_auth/urls.py
from django.urls import path, reverse_lazy, include
from users_auth import views
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)


app_name = "users_auth"
urlpatterns = [
    path("dashboard/", views.dashboard, name="dashboard"),
    path(
        "accounts/login/",
        LoginView.as_view(template_name="reg/login.html"),
        name="login",
    ),
    path(
        "accounts/logout/",
        LogoutView.as_view(template_name="logged_out.html"),
        name="logout",
    ),
    path(
        "accounts/password_change/",
        PasswordChangeView.as_view(
            template_name="reg/password_change_form.html",
            success_url=reverse_lazy("users_auth:password_change_done"),
        ),
        name="password_change",
    ),
    path(
        "accounts/password_change/done/",
        PasswordChangeDoneView.as_view(template_name="reg/password_change_done.html"),
        name="password_change_done",
    ),
    path("accouns/password_reset/", PasswordResetView.as_view(
        template_name='reg/password_reset_form.html',
        success_url = reverse_lazy("users_auth:password_reset_done"),
        email_template_name = "reg/password_reset_email.html"
        ), name="password_reset"),
    path(
        "account/password_reset/done/",
        PasswordResetDoneView.as_view(template_name='reg/password_reset_done.html'),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/", PasswordResetConfirmView.as_view(
            success_url=reverse_lazy("users_auth:password_reset_complete"),
            template_name="reg/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(
            template_name="reg/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("register/", views.register, name="register"),
    path("oauth/", include("social_django.urls")),
]

myproject/users_auth/models.py
from django.db import models

# Create your models here.

myproject/users_auth/forms.py
from django.contrib.auth.forms import UserCreationForm


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ("email",)

myproject/users_auth/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from users_auth.forms import CustomUserCreationForm
from django.urls import reverse

# from django.contrib.auth.urls


def dashboard(request):
    return render(request, "users/dashboard.html")


def register(request):
    if request.method == "GET":
        return render(
            request, "users/register.html",
            {"form": CustomUserCreationForm}
        )
    elif request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        print(f"form: {form.data}")
        print(f"form.errors: {form.errors}")
        if form.is_valid():
            print("+" * 80)
            user = form.save()
            login(request, user)
    return redirect(reverse("users_auth:dashboard"))

myproject/users_auth/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width={device-width}, initial-scale=1.0">
    <style>
        label,
        input {
            display: block;
        }
    
        span.helptext {
            display: none;
        }
    </style>
    {% block title %}
    <title>Document</title>
    {% endblock %}
</head>

<body>
    {% block heading %}
    <h1>My cute site</h1>
    <hr>
    <br>
    {% endblock %}

    {% block content %}
    {% endblock %}
</body>

</html>

myproject/users_auth/templates/reg/login.html
{% extends 'base.html' %}

{% block content %}
<h2>Login</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Login">
</form>
<p>
    <a href="{% url 'users_auth:dashboard' %}">Back to dashboard</a>
</p>
<p>
    <a href="{% url 'users_auth:password_reset' %}">Reset password</a>
</p>
<p>
    <a href="{% url 'users_auth:register' %}">Register</a>
</p>
<p>
    <a href="{% url 'social:begin' 'github' %}">Login with GitHub</a>
</p>
{% endblock %}

myproject/users_auth/templates/reg/password_change_done.html
{% extends 'base.html' %}

{% block content %}
<h2>Password changed</h2>

<a href="{% url 'users_auth:dashboard' %}">Back to dashboard</a>
{% endblock %}

myproject/users_auth/templates/reg/password_change_form.html
{% extends 'base.html' %}

{% block content %}
<h2>Change password</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Change">
</form>

<a href="{% url 'users_auth:dashboard' %}">Back to dashboard</a>
{% endblock %}

myproject/users_auth/templates/reg/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
<h2>Password reset complete</h2>

<a href="{% url 'users_auth:login' %}">Back to login</a>
{% endblock %}

myproject/users_auth/templates/reg/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
<h2>Confirm password reset</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Confirm">
</form>
{% endblock %}

myproject/users_auth/templates/reg/password_reset_done.html
{% extends 'base.html' %}

{% block content %}
<h2>Password reset done</h2>

<a href="{% url 'users_auth:login' %}">Back to login</a>
{% endblock %}

myproject/users_auth/templates/reg/password_reset_email.html
Some asked for paswword reset for email {{ email }}.
Follow the link bellow:
{{ protocol}}://{{ domain }}{% url 'users_auth:password_reset_confirm' uidb64=uid token=token %}

myproject/users_auth/templates/reg/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
<h2>Send password reset link</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Reset">
</form>

<a href="{% url 'users_auth:dashboard' %}">Back to dashboard</a>
{% endblock %}

myproject/users_auth/templates/users/dashboard.html
<!--users/templates/users/dashboard.html-->

{% extends 'base.html' %}

{% block content %}
Hello, {{ user.username|default:'Guest' }}!

<div>
    {% if user.is_authenticated %}
    <p>
        <a href="{% url 'users_auth:logout' %}">Logout</a>
    </p>
    <p>
        <a href="{% url 'users_auth:password_change' %}">Change password</a>
    </p>
    {% else %}
    <p>
        <a href="{% url 'users_auth:login' %}">Login</a>
    </p>
    {% endif %}
</div>

{% endblock %}

myproject/users_auth/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
<h2>Register</h2>

<form method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Register">
</form>

<a href="{% url 'users_auth:login' %}">Back to login</a>
{% endblock %}